### ISSUE TITLE
Net-ACME2-HTTP_Tiny requests escalated dramatically when DST Root CA X3 expired

### ISSUE THREAD

**Issue by ezekiel** [FGasper/p5-Net-ACME2#11]
Hi,

When `DST Root CA X3` expired, requests from this client against the Let's Encrypt API escalated dramatically ( especially against authorization endpoints like `/acme/authz-v3` ).
![image](https://user-images.githubusercontent.com/166399/135520645-0f50502f-caf5-4396-a2f1-19917a809bbd.png)

In response, we have had to apply a very strict ratelimit, which we hope to revert as soon as the problematic behavior in Net::ACME2 has been identified and fixed.

**Comment by FGasper** [comment]
@ezekiel Thank you for the heads-up … heh, maybe that explains why I was getting 429s against /directory. :)

Is this a bug report against Net::ACME2, or just an FYI?

**Comment by ezekiel** [comment]
This is a bug report against Net:;ACME2. I would like to help dig through chain validation and/or retry-with-backoff code, but figured better to get the report up quickly.

**Comment by FGasper** [comment]
> chain validation and/or retry-with-backoff code

There isn’t any. Net::ACME2 is just an interface to ACME; it doesn’t implement anything more.

**Comment by FGasper** [comment]
cPanel is a user of this module, though; their boxes are a likely source of the uptick in requests.

**Comment by FGasper** [comment]
I’m emailing you.

**Comment by ezekiel** [comment]
Ah! That's an information upgrade for me - okay, thank you.

**Comment by FGasper** [comment]
I‘m going to close this for now.
