### ISSUE TITLE
Expose agent property for HTTP::Tiny

### ISSUE THREAD

**Issue by twouters** [FGasper/p5-Net-ACME2#12]
Our implementation is impacted because of #11 and we're being rate-limited based on the library's user agent. 
 
I've worked my way around it by adding an `agent` arg to https://github.com/FGasper/p5-Net-ACME2/blob/5549a5ee3d5f53c2c2567fb5fd9e3a0f82d4bf05/lib/Net/ACME2/HTTP.pm#L48 but it would be nice if it could be propagated to Net::ACME2 so that we can use a distinct ~~username~~ user agent from CPanel's :slightly_smiling_face:

**Comment by FGasper** [comment]
@twouters You can do this by subclassing Net::ACME2::LetsEncrypt.

I’m not convinced that I want to add it to the interface.
