### ISSUE TITLE
Improper module version declaration

### ISSUE THREAD

**Issue by Grinnz** [FGasper/p5-Net-ACME2#4]
Two modules in this distribution have a version declared like this:

    our $VERSION;
    *VERSION = \$Net::ACME2::Constants::VERSION;

This is not a good idea for a couple reasons. Version declarations must be on a single line for PAUSE and other analysis tools to parse them; in this case they will simply parse the version as undef. Secondly, the version should not be assigned from an external dependency, it should be declared statically; even if you put it in the line parsed by PAUSE, the current version of Net/ACME2/Constants.pm in this distribution will not be loaded at that time. The version must be wholly constructed from evaluating only that line. I recommend using a tool like https://metacpan.org/pod/App::RewriteVersion (the two scripts it comes with) to maintain versions across multiple modules when not using Dist::Zilla.

**Comment by FGasper** [comment]
@Grinnz E::MM allows a `VERSION_FROM` directive, which seems to take care of the PAUSE problem, no?

I would rather not have to load the main module just to find out the distribution’s version number.

Can you point to something that this actually breaks? If versions are meant only to be declared statically, what purpose is `VERSION_FROM` meant to serve?

**Comment by Grinnz** [comment]
ExtUtils::MakeMaker is unrelated to PAUSE parsing of versions. What you refer to is how the distribution version is set, EUMM uses that information to determine the distribution version to set in metadata. Module versions are parsed individually by PAUSE in order to index the modules for installation, like `cpanm Net::ACME2`.

**Comment by FGasper** [comment]
So basically, nothing should use ‘VERSION_FROM’?

I don’t mean to be difficult, but I’m curious why toolchain has a feature like that if it screws up PAUSE.

**Comment by Grinnz** [comment]
Sorry if I'm not being clear. This has nothing to do with VERSION_FROM and you are using that correctly.

**Comment by Grinnz** [comment]
Let me try to explain this a bit better. There are two types of "items" being versioned; each module, and the distribution as a whole. PAUSE deals in module versions only, when you upload a distribution (and it's not a dev release) it looks for every package in the distribution, and looks for where $VERSION is first declared in that package, and evaluates only that line to get the version for that package. It then determines if that is a higher version than it currently has indexed for that module (or if it doesn't have that module indexed yet), and whether you have PAUSE permissions for that module name, and checks the metadata related to whether that module should be indexed (see https://github.com/andk/pause/blob/master/doc/operating-model.md#35-factors-considering-in-the-indexing-phase for specifics). If that all passes, it updates the [module index](https://cpanmeta.grinnz.com/packages) to point that module name at that release, with the version it found. Then when someone runs `cpanm Some::Module` it looks up in that index what release to install, and each module in the distribution will have its own entry in the index, pointing to the same release (if they're properly versioned).

Separately, there is a distribution version; this is what ExtUtils::MakeMaker needs to set in metadata for the distribution, and VERSION_FROM is one way to tell EUMM where to find it. This however is not directly used by PAUSE at all, except that the distribution version ends up in the archive name, and it disallows uploading archives with the exact same name. Your usage of this is correct, you have VERSION_FROM set to a module with a statically parseable version.

But in the other modules you have versions which are not possible for PAUSE to statically parse for indexing purposes. My suggestion is to declare the same version in those modules as you have in Net::ACME2::Constants, and use a tool like perl-rewrite-version to update all the versions together, rather than having them programatically depend on each other.

I hope that helps clear it up.

**Comment by FGasper** [comment]
That does make more sense, yes.

Is there a feature request somewhere to have PAUSE bug people about this when it detects it? I don’t use `cpanm`, so I guess that’s why this hasn’t bitten me personally.

**Comment by FGasper** [comment]
I’ve uploaded 0.2-TRIAL3, which should address this issue.

**Comment by Grinnz** [comment]
It's not really an error for a module to be missing a version, many people upload distributions with only a few of the modules containing versions, so it's tough to say what PAUSE should consider an error there; maybe it should warn you if the "main module" (which it defines as the module matching the distribution name) is missing a version at least. In this case it wouldn't have warned you yet, since the indexer is what does this analysis and it doesn't run at all for TRIAL releases. But you should always define versions for modules you expect people to declare as dependencies (this is the other use of the module-specific versions I forgot to mention). Module version use for installation and dependency resolution works the same with cpanm or any other cpan client, I just used cpanm as an example.

One slight problem in the new upload, your module versions should only be '0.2'; Perl module/dist versions cannot contain letters or hyphens, the -TRIAL part is only needed in the archive name to prevent indexing. (Some choose to add a # TRIAL comment to the version declaration so there's an indication there, which is supported by App::RewriteVersion with the --trial option, though it doesn't matter practically speaking.)

**Comment by Grinnz** [comment]
Ah, I see. Well without -TRIAL in the version you should be able to remove the s/// operation at least. The other thing it needs to handle however is when VERSION is called with an argument, because UNIVERSAL::VERSION is also expected to be usable this way. I think the easiest way to handle this would be to just set $VERSION similar to how it is in Net::ACME2, because UNIVERSAL::VERSION will use this by default, so you shouldn't need to override the method. Otherwise, you essentially have to reimplement UNIVERSAL::VERSION which is pretty ugly: https://metacpan.org/source/JPEACOCK/version-0.9924/vperl/vpp.pm#L933

**Comment by Grinnz** [comment]
Description of UNIVERSAL::VERSION: https://metacpan.org/pod/UNIVERSAL#VERSION-(-[-REQUIRE-]-)

**Comment by Grinnz** [comment]
Alternatively, you could do something like this, which will just fail any version checks other than 0 (which seems acceptable here):

```
sub VERSION {
    my $inv = shift;
    return $Net::ACME2::VERSION unless @_;
    return $inv->SUPER::VERSION(@_);
}
```
